### ISSUE TITLE
VB-1: Update User model

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#84]
Update User model as described below:

== Enums ==

```
    Role:
        - administrator
        - coordinator
        - operator

    WeekDay:
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday 
```

== Classes ==

   ```
    User:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type : string
        phone:
          type: string
        role:
          type: List of Role
        is_active:
          type: boolean
        availability_hours_start:
          type: integer
        availability_hours_end:
          type: integer
        availability_days:
          type: List of WeekDay
       last_access:
          type: date-time
       created_at:
          type: date-time
      required:
        - email
        - password
        - address
        - zone
        - phone
```

Fields that are not mentioned should be moved at the end of User model and marked as deprecated.
