### ISSUE TITLE
VB-5: Update Volunteer model

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#88]
1. Volunteer model should extends `Document` directly.
2. Add enums associated with the volunteer model:

```
    VolunteerRole:
        - delivery
        - copilot
        - packing
        - supply
        - operator

    VolunteerStatus:
        - active
        - inactive
        - blacklist

    Zone:
        - botanica
        - buiucani
        - centru
        - ciocana
        - riscani
        - telecentru
        - suburbii
```
3. Add new fields for Volunteer model:
- first_name
- last_name
- phone
- email
- role
- status
- availability_hours_start
- availability_hours_end 
- created_at

Fields that are not mentioned should be moved at the end of Volunteer model and marked as deprecated.
