### ISSUE TITLE
VB-8: Create Request model

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#91]
1. Add enums associated with the request model:
```
    RequestsStatus:
        - new
        - confirmed
        - in_process
        - canceled
        - solved
        - archived
```
2. Create Request model as described below:
```
    Request:
       beneficiary:
          type: Beneficiary
       user:
          type: User
       status:
          type: RequestStatus
       secret:
          type: string
       urgent:
          type: boolean
       comments:
          type: string
       has_symptoms:
          type: boolean
       cluster:
          type: Cluster
       created_at:
          type: date-time
      required:
        - beneficiary
        - user
        - status
```
