### ISSUE TITLE
VB-9: Create Notification model

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#92]
1. Add enums associated with the notification model:
```
    NotificationType:
        - new_request
        - canceled_request
```
2. Create Notification model as described below:
```
    Notification:
       type:
          type: NotificationType
       subject:
          type: string
       request:
          type: Request
       created_at:
          type: date-time
      required:
        - type
        - request
```
