### ISSUE TITLE
VB-10: Create NotificationUser model

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#93]
1. Add enums associated with the NotificationUser model:
```
    NotificationStatus:
        - new
        - seen
        - deleted
```
2. Create NotificationUser model as described below:
```
    NotificationUser:
       user:
          type: User
       status:
          type: NotificationStatus
       notification:
          type: Notification
       created_at:
          type: datetime
       required:
        - user
        - status
        - notification
```
